### ISSUE TITLE
Controlador LogBoxSD

### ISSUE THREAD

**Issue by sebablasko** [niclabs/KippZonen-ServiceMode-Library#3]
Construir una clase que permita la interacción con un service Mode del LogBox SD.
Este controlador debe contemplar:
 - Implementar los comandos propios del SM que atañen al uso en la recuperación de datos
 - Llevar un estado para saber los comandos disponibles en cada nivel del SM
 - Contemplar el uso de un Objeto que implemente la interfaz de la clase ```Conexion``` y el uso de sus métodos.

**Comment by JoseTapiaG** [comment]
9f01270a1db588f7301e0104ed1076d767aa3447
